# Generated by Django 2.2 on 2019-04-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', models.IntegerField()),
                ('squares', models.IntegerField()),
                ('cards', models.IntegerField()),
                ('sequence', models.CharField(max_length=100)),
                ('card_list', models.CharField(max_length=1000)),
                ('result', models.CharField(max_length=100)),
            ],
        ),
    ]
